services:
  neutron-npu-passthrough-on-nxp-i.mx95:
    container_name: neutron-npu-passthrough-on-nxp-i.mx95
    image: harbor.edgesync.cloud/nycu-cosmos-lab/neutron-npu-passthrough-on-nxp-i.mx95
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    environment:
      - DEBIAN_FRONTEND=noninteractive
    working_dir: /workspace
    devices:
      - /dev/neutron0
    volumes:
      - /dev:/dev
    entrypoint: ["/bin/bash"]
    network_mode: host
    stdin_open: true
    tty: true
    restart: always